# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hereditatem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(blank=True)),
                ('height', models.FloatField(blank=True)),
                ('thickness', models.FloatField(blank=True)),
                ('back_scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hereditatem.Scan2D')),
                ('front_scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hereditatem.Scan2D')),
            ],
        ),
    ]
