# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hereditatem', '0002_fragment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragment',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
    ]
