# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hereditatem', '0003_fragment_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragment',
            name='back_scan',
            field=models.ImageField(upload_to='fragments_img/'),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='front_scan',
            field=models.ImageField(upload_to='fragments_img/'),
        ),
        migrations.DeleteModel(
            name='Scan2D',
        ),
    ]
