# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hereditatem', '0004_auto_20180819_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragment',
            name='original_back_scan',
            field=models.ImageField(null=True, upload_to='fragments_img/originals/'),
        ),
        migrations.AddField(
            model_name='fragment',
            name='original_front_scan',
            field=models.ImageField(null=True, upload_to='fragments_img/originals/'),
        ),
    ]
